### ISSUE TITLE
Improvements generici - priorità bassa ma bella)

### ISSUE THREAD

**Issue by capitanevs** [lucarebuffi/WISE#3]
**Cursori sui grafici**
Usando operativamente WISE@OASYS abbiamo sentito la mancanza del cursore nei grafici: per intenderci, quello nativo dei grafici matplotlib che consente di fare misure precise nel grafico. Pensi si possa aggiungere come feature a tutti i plot in genere?

**Barre di avanzamento**
Mettere barre di avanzamento duranti i calcoli (che, risolti gli altri issues, saranno lanciati solo dal pupolo detector). Sia per il calcolo singolo, che per il find best focus. Anche uno stop button non sarebbe male.

**Comment by lucarebuffi** [comment]
Cursori: propago la richiesta agli sviluppatori delle librerie di plot (ESRF).
Barre: Le barre di avanzamento ci sono già, solo che non le avete viste. Non verranno in ogni caso aggiunte altre barre.
Bottone Stop: ok

**Comment by lucarebuffi** [comment]
I cursori erano già presenti nella libreria grafica, è stato sufficiente attivarli.

**Comment by capitanevs** [comment]
Rock'n roll Luca!
